### ISSUE TITLE
Unable to see description

### ISSUE THREAD

**Issue by gvol** [BriansEmacs/insert-pair-edit.el#2]
When I hit Enter on the `ipe` package in the `*Packages*` buffer, I get the error:

    Wrong type argument: listp, "Brian Kavanagh (concat \"Brians.Emacs\" \"@\" \"gmail.com\")"

and the `*Help*` buffer is only partially filled it.  (Un)fortunately, it doesn't give a backtrace, probably because the package system is catching the error.

**Comment by gvol** [comment]
I guess I should say that I'm using a version I built from git about a week ago, so it could be a problem only on recent versions.

**Comment by BriansEmacs** [comment]
Hi Ivan,

   Do you get the same problem if you try installing from MELPA?  (Trying
to debug a "local build" could be very difficult)

- Brian

**Comment by BriansEmacs** [comment]
Hi Ivan,

  Any luck with attempting that install from MELPA?

- Brian.

**Comment by gvol** [comment]
Sorry, I realize I was unclear.  I'm using a new version of Emacs that I built myself, not a version of `ipe` that I built.  

I was trying to install from MELPA.  I ran `package-list-packages`, search for `ipe` and then hit enter and that's when it gives me the error.  It actually installs fine, it just won't show me information about the package.

**Comment by BriansEmacs** [comment]
Hi Ivan,

  Thank you for the reply (and for the clarification).  I suspect your issue is caused by the way in which I was specifying my email address in the elisp headers.  It is unconventional (as I was hoping to avoid automated spam on this account)  but it may be that some versions of `package.el` are performing more parsing on this field than the versions on which I am performing my testing.

  What version of Emacs is your local build using?  I'll see if I can repeat the problem locally.   If not, I guess I may end up changing the elisp headers to include a more conventional email field.

   Thank you for your interest!

- Brian

**Comment by gvol** [comment]
> What version of Emacs is your local build using? 

It's version "30.0.50", namely built off of trunk with a few patches on top of commit 55a200d7071320311365787b60f311c7c91922d8.

**Comment by BriansEmacs** [comment]
Hi Ivan,

  I've patched up the elisp headers in the `ipe*.el` files to use the format:
  
```
;; Maintainer: name <email>
```
   
  I'm (fairly) certain this should fix the problems you were encountering with your **Emacs 30.x** build being unable to parse the `ipe` package.  Looking at the **Emacs 30** [source](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/package.el), it seems that this is a change to the `package.el` that may break some existing behavior.   I don't think that the `ipe` packages will be the only one on **MELPA** that will encounter this issue if the existing **Emacs 30** `package.el` code remains in its current form. I can see other **MELPA** packages which don't seem to include a "<" email ">" within their `Maintainers` .  Looking at the current [elisp](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html) doco, it appears that the use of the "<" email ">" is still only a suggestion, so It may be that this should really be raised as an **Emacs 30** `package.el` bug.  
  
  Anyway, hopefully the latest `ipe` MELPA Version should now work for you (once the current MELPA build is finished).  Give it a try.
  
- Brian.

**Comment by BriansEmacs** [comment]
Hi Ivan, 

  Did that fix your problem?  May I close this issue?

- Brian

**Comment by gvol** [comment]
Yes, it's fixed.

Sorry, I swear I replied to this already, but clearly not.
